### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by zhoux121** [HighwayWu/SIFT-Reconstruction#2]
Hi Highway Wu 
I encounter an out-of-index problem in your code. If you can help me to solve these issues, I will be very grateful.
comment: python main.py --model SLI-L train
my dataset is from your SIFT_Recmstruction_Weights
![image](https://user-images.githubusercontent.com/21269237/120900579-767c6f00-c603-11eb-837e-d420ebba5b35.png)

**Comment by HighwayWu** [comment]
Hi zhoux121:
This error is because the code can't load your training data. Actually I think it would be better to rewrite this "Dataset" as your preference. That's would be more convenient for your usage.

**Comment by zhoux121** [comment]
Hi, Highway thanks for your reply. I want to run your Train demo, but it looks like there are some issues for me. I am very new to this, and I have correctly put your demo data file in the correct path. And it still has the out-of-index issues.

**Comment by zhoux121** [comment]
> Hi zhoux121：
> 这个错误是因为代码无法加载你的训练数据。实际上，我认为根据您的喜好重写这个“数据集”会更好。这样会更方便您的使用。

您好，公路感谢您的回复。我想运行您的火车演示，但我好像遇到了一些问题。我很认可，我已经正确地将您的演示数据文件了正确的路径中。它是否存在存在的外在问题。
