### ISSUE TITLE
Question about the image shape

### ISSUE THREAD

**Issue by zhoux121** [HighwayWu/SIFT-Reconstruction#3]
Hi Highway Wu, 
Is it possible to keep the original image size? For example, my original image is 720x480. At your main.py line 87, do we have to resize our image as a shaped square?
Thank you so much!

**Comment by HighwayWu** [comment]
Hi zhoux121,

Sorry that the image size should be at least 256 (or multiple of 256), as there are totally 8 up/down sampling in the network structure. Or you may replace the network by other architecture to suit your needs.

**Comment by zhoux121** [comment]
Hi Highway Wu
Thank you for your reply.
